# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

port: 4001
name: Sanket Parmar
home_title: Home | Sanketio
email: sanket.parmar11@gmail.com
description: I'm having 11+ years of experience as a WordPress (PHP) developer and focused on developing innovative solutions for diverse industries.
baseurl: '' # the subpath of your site, e.g. /blog
url: https://sanketio.github.io # the base hostname & protocol for your site, e.g. http://example.com
logo: https://sanketio.github.io/src/images/emojis/technologist.png
cover: https://sanketio.github.io/src/images/og.png
social:
  - title: email
    url: mailto:sanket.parmar11@gmail.com
  - title: github
    url: https://github.com/bchiang7
  - title: wordpress
    url: https://profiles.wordpress.org/sanketparmar/
  - title: linkedin
    url: https://www.linkedin.com/in/sanketio
  - title: twitter
    url: https://twitter.com/Sanketio
  - title: instagram
    url: https://instagram.com/snketio
  - title: facebook
    url: https://www.facebook.com/sanketio

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
